{% set name = "llvmlite" %}
{% set version = "0.33.0" %}
{% set build_number = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/numba/llvmlite
  git_rev: v{{ version }}
  patches:
    - 0001-link-static.patch

build:
  number: {{ build_number }}
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [not (osx or armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }}  # [not (osx or armv6l or armv7l or aarch64)]
    # The DLL build uses cmake on Windows
    - cmake          # [win]
    - make           # [unix and not (armv6l or armv7l or aarch64)]
  host:
    - python
    # On channel https://anaconda.org/numba/
    # ppc64le needs LLVM 7 series, LLVM 8 has issues
    - llvmdev 9.0.1 *_1
    - vs2015_runtime # [win]
    - enum34         # [py27]
    # llvmdev is built with libz compression support
    - zlib           # [unix and not (armv6l or armv7l or aarch64)]
  run:
    - python
    - enum34         # [py27]
    - vs2015_runtime # [win]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1 # [osx]
    - libllvm9 9.0.1 *_1

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
