{% set version = "1.1.0" %}

package:
    name: mkl_fft
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl_fft/archive/v{{version}}.tar.gz
    sha256: bad1b957e457e9dc596b54047c741df5b6e78f677e2c8a67b62d8cbf2ce9ae83

build:
  number: 0
  skip: True  # [ppc64le]
  script: {{PYTHON}} setup.py build install --single-version-externally-managed --record=record.txt

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
    host:
      - python
      - setuptools
      - mkl-devel  {{ mkl }}
      - cython
      - numpy-devel  {{ numpy }}
    run:
      - python

test:
    commands:
      - nosetests -v mkl_fft
    requires:
      - nose
    imports:
      - mkl_fft
      - mkl_fft._numpy_fft
      - mkl_fft._scipy_fft

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    description:
        NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.
        Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision
        with arbitrary memory layout, so long as array strides are multiples of its itemsize.
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.

extra:
  recipe-maintainers:
     - oleksandr-pavlyk
