{% set version = "3.8.0" %}

package:
  name: libprotobuf
  version: {{ version }}

source:
  - url: https://github.com/google/protobuf/archive/v{{ version }}/libprotobuf-v{{ version }}.tar.gz
    sha256: 03d2e5ef101aee4c2f6ddcf145d2a04926b9c19e7086944df3842b1b8502b783
    patches:
      - 0001-remove-Werror-from-test-flags.patch  # [ppc64le]
  # these are git submodules from the 3.8.0 release
  # https://github.com/google/protobuf/tree/v3.8.0/third_party
  - url: https://github.com/google/benchmark/archive/5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8.zip
    sha256: 866d3c8cadb3323251d4fe0e989ea0df51f30660badb73dad0f2d11e5bf1770f
    folder: third_party/benchmark
  - url: https://github.com/google/googletest/archive/5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081.zip
    sha256: 629ba44a7dbc633da0add633b675add1810cd4f2e8e08558893de94b56a5808c
    folder: third_party/googletest

build:
  number: 0
  # Requires C++ 11, VS 2008 is not supported
  skip: True  # [win and vc<14]
  run_exports:
    # breaks backwards compatibility and new SONAME each minor release
    # https://abi-laboratory.pro/tracker/timeline/protobuf/
    # One exception was that 3.6.1 was incompatible with 3.6.0
    - {{ pin_subpackage('libprotobuf', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - unzip  # [not win]
    - make  # [not win]
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a  # [not win]
    - test -f ${PREFIX}/lib/libprotobuf${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\libprotoc.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf-lite.lib exit 1  # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format. C++ Libraries"
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/
  doc_source_url: https://github.com/google/protobuf/releases

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
    - xhochy
